#!/usr/bin/env python3
#
# This script is in the public domain
#
# Author: Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>
#
# This script accepts a tarball on standard input and filters it according to
# the same rules used by dpkg --path-exclude and --path-include, using command
# line options of the same name. The result is then printed on standard output.
#
# A tool like this should be written in C but libarchive has issues:
# https://github.com/libarchive/libarchive/issues/587
# https://github.com/libarchive/libarchive/pull/1288/ (needs 3.4.1)
# Should these issues get fixed, then a good template is tarfilter.c in the
# examples directory of libarchive.
#
# We are not using Perl either, because Archive::Tar slurps the whole tarball
# into memory.
#
# We could also use Go but meh...
# https://stackoverflow.com/a/59542307/784669

import tarfile
import sys
import argparse
import fnmatch
import re


class PathFilterAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        items = getattr(namespace, "pathfilter", [])
        regex = re.compile(fnmatch.translate(values))
        items.append((self.dest, regex))
        setattr(namespace, "pathfilter", items)


class PaxFilterAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        items = getattr(namespace, "paxfilter", [])
        regex = re.compile(fnmatch.translate(values))
        items.append((self.dest, regex))
        setattr(namespace, "paxfilter", items)


class TypeFilterAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        items = getattr(namespace, "typefilter", [])
        match values:
            case "REGTYPE" | "0":
                items.append(tarfile.REGTYPE)
            case "LNKTYPE" | "1":
                items.append(tarfile.LNKTYPE)
            case "SYMTYPE" | "2":
                items.append(tarfile.SYMTYPE)
            case "CHRTYPE" | "3":
                items.append(tarfile.CHRTYPE)
            case "BLKTYPE" | "4":
                items.append(tarfile.BLKTYPE)
            case "DIRTYPE" | "5":
                items.append(tarfile.DIRTYPE)
            case "FIFOTYPE" | "6":
                items.append(tarfile.FIFOTYPE)
            case _:
                raise ValueError("invalid type: %s" % values)
        setattr(namespace, "typefilter", items)


def _find_unescaped_delimiter(expression, delimiter, start):
    backslashes = 0
    for index in range(start, len(expression)):
        char = expression[index]
        if char == "\\":
            backslashes += 1
            continue
        if char == delimiter and backslashes % 2 == 0:
            return index
        backslashes = 0
    return -1


def _unescape_delimiter(value, delimiter):
    result = []
    index = 0
    while index < len(value):
        if (
            value[index] == "\\"
            and index + 1 < len(value)
            and value[index + 1] == delimiter
        ):
            result.append(delimiter)
            index += 2
            continue
        result.append(value[index])
        index += 1
    return "".join(result)


def _sed_replacement(template, delimiter):
    def replace(match):
        result = []
        index = 0
        while index < len(template):
            char = template[index]
            if char == "&":
                result.append(match.group(0))
                index += 1
                continue
            if char != "\\":
                result.append(char)
                index += 1
                continue
            if index + 1 == len(template):
                result.append("\\")
                index += 1
                continue
            escaped = template[index + 1]
            if escaped in "123456789":
                group = match.group(int(escaped))
                if group is not None:
                    result.append(group)
            elif escaped in ("&", "\\", delimiter):
                result.append(escaped)
            else:
                result.append(escaped)
            index += 2
        return "".join(result)

    return replace


def _sed_substitute(regex, replacement, value, occurrence, global_after):
    selected = occurrence if occurrence > 0 else 1
    seen = 0

    def replace_selected(match):
        nonlocal seen
        seen += 1
        if seen < selected:
            return match.group(0)
        if seen == selected or global_after:
            return replacement(match)
        return match.group(0)

    return regex.sub(replace_selected, value)


class TransformAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        items = getattr(namespace, "trans", [])
        # This function mimics what src/transform.c from tar does
        if not values.startswith("s"):
            raise ValueError("regex must start with an 's'")
        if len(values) <= 4:
            # minimum regex: s/x//
            raise ValueError("invalid regex (too short)")
        delimiter = values[1]
        pattern_end = _find_unescaped_delimiter(values, delimiter, 2)
        if pattern_end == -1:
            raise ValueError("invalid regex: missing pattern delimiter")
        replacement_end = _find_unescaped_delimiter(
            values, delimiter, pattern_end + 1
        )
        if replacement_end == -1:
            raise ValueError("invalid regex: missing replacement delimiter")
        pattern = values[2:pattern_end]
        replacement = values[pattern_end + 1 : replacement_end]
        flag_text = values[replacement_end + 1 :]
        if not pattern:
            raise ValueError("empty regex")

        supported = {"g", "i", "r", "R", "s", "S", "h", "H"}
        unsupported = sorted(
            set(flag for flag in flag_text if flag not in "0123456789") - supported
        )
        if unsupported:
            raise ValueError("unsupported transform flags: %s" % "".join(unsupported))
        duplicates = sorted(flag for flag in supported if flag_text.count(flag) > 1)
        if duplicates:
            raise ValueError("duplicate transform flags: %s" % "".join(duplicates))

        flags = 0
        if "i" in flag_text:
            flags = re.IGNORECASE
        occurrence = 0
        number_text = ""
        scopes = {"r": True, "s": True, "h": True}
        for flag in flag_text:
            if flag in "0123456789":
                number_text += flag
                continue
            if number_text:
                occurrence = int(number_text)
                number_text = ""
            if flag in scopes:
                scopes[flag] = True
            elif flag in {"R", "S", "H"}:
                scopes[flag.lower()] = False
        if number_text:
            occurrence = int(number_text)
        pattern = _unescape_delimiter(pattern, delimiter)
        items.append(
            (
                re.compile(pattern, flags),
                _sed_replacement(replacement, delimiter),
                occurrence,
                "g" in flag_text,
                scopes,
            )
        )
        setattr(namespace, "trans", items)


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""\
Filters a tarball on standard input by the same rules as the dpkg --path-exclude
and --path-include options and writes resulting tarball to standard output. See
dpkg(1) for information on how these two options work in detail. To reuse the
exact same semantics as used by dpkg, paths must be given as /path and not as
./path even though they might be stored as such in the tarball.

Secondly, filter out unwanted pax extended headers using --pax-exclude and
--pax-include. This is useful in cases where a tool only accepts certain xattr
prefixes. For example tar2sqfs only supports SCHILY.xattr.user.*,
SCHILY.xattr.trusted.* and SCHILY.xattr.security.* but not
SCHILY.xattr.system.posix_acl_default.*.

Both types of options use Unix shell-style wildcards:

       * matches everything
       ? matches any single character
   [seq] matches any character in seq
  [!seq] matches any character not in seq

Thirdly, filter out files matching a specific tar archive member type using
--type-exclude. Valid type names are REGTYPE (regular file), LNKTYPE
(hardlink), SYMTYPE (symlink), CHRTYPE (character special), BLKTYPE (block
special), DIRTYPE (directory), FIFOTYPE (fifo) or their tar format flag value
(0-6, respectively).

Fourthly, transform the path of tar members using a sed expression just as with
GNU tar --transform.

Fifthly, strip leading directory components off of tar members. Just as with
GNU tar --strip-components, tar members that have less or equal components in
their path are not passed through.

Lastly, shift user id and group id of each entry by the value given by the
--idshift argument. The resulting uid or gid must not be negative.
""",
    )
    parser.add_argument(
        "--path-exclude",
        metavar="pattern",
        action=PathFilterAction,
        help="Exclude path matching the given shell pattern. "
        "This option can be specified multiple times.",
    )
    parser.add_argument(
        "--path-include",
        metavar="pattern",
        action=PathFilterAction,
        help="Re-include a pattern after a previous exclusion. "
        "This option can be specified multiple times.",
    )
    parser.add_argument(
        "--pax-exclude",
        metavar="pattern",
        action=PaxFilterAction,
        help="Exclude pax header matching the given globbing pattern. "
        "This option can be specified multiple times.",
    )
    parser.add_argument(
        "--pax-include",
        metavar="pattern",
        action=PaxFilterAction,
        help="Re-include a pax header after a previous exclusion. "
        "This option can be specified multiple times.",
    )
    parser.add_argument(
        "--type-exclude",
        metavar="type",
        action=TypeFilterAction,
        help="Exclude certain member types by their type. Choose types either "
        "by their name (REGTYPE, LNKTYPE, SYMTYPE, CHRTYPE, BLKTYPE, DIRTYPE, "
        "FIFOTYPE) or by their tar format flag values (0-6, respectively). "
        "This option can be specified multiple times.",
    )
    parser.add_argument(
        "--transform",
        "--xform",
        metavar="EXPRESSION",
        action=TransformAction,
        help="Use sed replace EXPRESSION to transform file names. "
        "This option can be specified multiple times.",
    )
    parser.add_argument(
        "--strip-components",
        metavar="NUMBER",
        type=int,
        help="Strip NUMBER leading components from file names",
    )
    parser.add_argument(
        "--idshift",
        metavar="NUM",
        type=int,
        help="Integer value by which to shift the uid and gid of each entry",
    )
    args = parser.parse_args()
    if (
        not hasattr(args, "pathfilter")
        and not hasattr(args, "paxfilter")
        and not hasattr(args, "typefilter")
        and not hasattr(args, "strip_components")
    ):
        from shutil import copyfileobj

        copyfileobj(sys.stdin.buffer, sys.stdout.buffer)
        exit()

    # same logic as in dpkg/src/filters.c/filter_should_skip()
    prefix_prog = re.compile(r"^([^*?[\\]*).*")

    def path_filter_should_skip(member):
        skip = False
        if not hasattr(args, "pathfilter"):
            return False
        # normalize path and make it absolute by stripping off all leading
        # dots and slashes and then prepending a slash
        name = "/" + member.name.lstrip("./")
        for t, r in args.pathfilter:
            if r.match(name) is not None:
                if t == "path_include":
                    skip = False
                else:
                    skip = True
        if skip and (member.isdir() or member.issym()):
            for t, r in args.pathfilter:
                if t != "path_include":
                    continue
                prefix = prefix_prog.sub(r"\1", r.pattern)
                prefix = prefix.rstrip("/")
                if name.startswith(prefix):
                    return False
        return skip

    def pax_filter_should_skip(header):
        if not hasattr(args, "paxfilter"):
            return False
        skip = False
        for t, r in args.paxfilter:
            if r.match(header) is None:
                continue
            if t == "pax_include":
                skip = False
            else:
                skip = True
        return skip

    def type_filter_should_skip(member):
        if not hasattr(args, "typefilter"):
            return False
        for t in args.typefilter:
            if member.type == t:
                return True
        return False

    # starting with Python 3.8, the default format became PAX_FORMAT but we
    # are still explicit here in case of future changes.
    with tarfile.open(fileobj=sys.stdin.buffer, mode="r|*") as in_tar, tarfile.open(
        fileobj=sys.stdout.buffer, mode="w|", format=tarfile.PAX_FORMAT
    ) as out_tar:
        for member in in_tar:
            if path_filter_should_skip(member):
                continue
            if type_filter_should_skip(member):
                continue
            if args.strip_components:
                comps = member.name.split("/")
                # just as with GNU tar, archive members with less or equal
                # number of components are not passed through at all
                if len(comps) <= args.strip_components:
                    continue
                member.name = "/".join(comps[args.strip_components :])
                member.pax_headers.pop("path", None)
                if member.islnk():
                    link_comps = member.linkname.split("/")
                    if len(link_comps) <= args.strip_components:
                        continue
                    member.linkname = "/".join(
                        link_comps[args.strip_components :]
                    )
                    member.pax_headers.pop("linkpath", None)
            member.pax_headers = {
                k: v
                for k, v in member.pax_headers.items()
                if not pax_filter_should_skip(k)
            }
            if args.idshift:
                if args.idshift < 0 and -args.idshift > member.uid:
                    print("uid cannot be negative", file=sys.stderr)
                    exit(1)
                if args.idshift < 0 and -args.idshift > member.gid:
                    print("gid cannot be negative", file=sys.stderr)
                    exit(1)
                member.uid += args.idshift
                member.gid += args.idshift
            if hasattr(args, "trans"):
                original_name = member.name
                original_linkname = member.linkname
                for (
                    regex,
                    replacement,
                    occurrence,
                    global_after,
                    scopes,
                ) in args.trans:
                    if scopes["r"]:
                        member.name = _sed_substitute(
                            regex,
                            replacement,
                            member.name,
                            occurrence,
                            global_after,
                        )
                    if member.islnk() and scopes["h"]:
                        member.linkname = _sed_substitute(
                            regex,
                            replacement,
                            member.linkname,
                            occurrence,
                            global_after,
                        )
                    elif member.issym() and scopes["s"]:
                        member.linkname = _sed_substitute(
                            regex,
                            replacement,
                            member.linkname,
                            occurrence,
                            global_after,
                        )
                if member.name != original_name:
                    member.pax_headers.pop("path", None)
                if (
                    (member.islnk() or member.issym())
                    and member.linkname != original_linkname
                ):
                    member.pax_headers.pop("linkpath", None)
            if member.isfile():
                with in_tar.extractfile(member) as file:
                    out_tar.addfile(member, file)
            else:
                out_tar.addfile(member)


if __name__ == "__main__":
    main()
