#!/bin/sh
set -eu
export LC_ALL=C.UTF-8
trap "rm -f /tmp/debian-chroot.tar" EXIT INT TERM
{{ CMD }} --mode={{ MODE }} --variant=custom \
  --include "$(tr '\n' ',' <pkglist.txt)" \
  --aptopt='APT::Solver "aspcud"' \
  {{ DIST }} /tmp/debian-chroot.tar {{ MIRROR }}
{
  tar -tf /tmp/debian-chroot.tar
  echo ./var/lib/apt/extended_states
} | sort \
  | grep -v '^./etc/apt/apt.conf.d/99mmdebstrap$' \
  | diff -u tar1.txt -
