#!/bin/sh
set -eu
export LC_ALL=C.UTF-8
export SOURCE_DATE_EPOCH={{ SOURCE_DATE_EPOCH }}

[ {{ MODE }} = "unshare" ]

trap "rm -f /tmp/debian-chroot.tar" EXIT INT TERM

prefix=
if [ "$(id -u)" -eq 0 ] && [ "{{ MODE }}" != "root" ] && [ "{{ MODE }}" != "auto" ]; then
  if ! id "${SUDO_USER:-user}" >/dev/null 2>&1; then
    if [ ! -e /mmdebstrap-testenv ]; then
      echo "this test modifies the system and should only be run inside a container" >&2
      exit 1
    fi
    useradd --home-dir "/home/${SUDO_USER:-user}" --create-home "${SUDO_USER:-user}"
  fi
  prefix="runuser -u ${SUDO_USER:-user} --"
fi

MMTARFILTER=
[ -x /usr/bin/mmtarfilter ] && MMTARFILTER=/usr/bin/mmtarfilter
[ -x ./tarfilter ] && MMTARFILTER=./tarfilter

$prefix {{ CMD }} --mode={{ MODE }} --variant=apt \
  --skip=output/dev \
  --customize-hook='chroot "$1" sh -c "sleep 1m > /dev/null" &' \
  {{ DIST }} - {{ MIRROR }} \
  | "$MMTARFILTER" --path-exclude="/dev" \
    >/tmp/debian-chroot.tar

origfilter() {
  "$MMTARFILTER" <./cache/mmdebstrap-{{ DIST }}-apt.tar --path-exclude="/dev/*" --path-exclude="/dev"
}

origfilter | cmp - /tmp/debian-chroot.tar \
  || origfilter | diffoscope - /tmp/debian-chroot.tar
